### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by avnerh1** [DrMoriarty/godot-ios-att#1]
What are the `Dev Key` and `Apple App Id` used for?
Where can I obtain the `Dev Key`?

I was unable to find the answers in the documentation nor in the code (this one or Apple's).

**Comment by DrMoriarty** [comment]
Are you asking about godot export parameters? This plugin has no any settings which you should to setup.

**Comment by avnerh1** [comment]
My mistake - sorry, it was late :)
Issue solved. Sorry for troubling you.
