### ISSUE TITLE
Suggestion for iOS<14

### ISSUE THREAD

**Issue by avnerh1** [DrMoriarty/godot-ios-att#2]
It is my understanding that if the plugin is used with iOS version<14, the plugin does nothing and status is always 0.
For the sake of one-flow, it's better to handle old iOS versions this way:
1. `status()` will always return 3
2. `request()` will still fire the signal `requestCompleted`.

**Comment by DrMoriarty** [comment]
Good idea. I definitely will make this.

**Comment by DrMoriarty** [comment]
fixed in v 1.0.1
